baseurl: https://aviswebsite.netlify.app
title: Avis Creative portfolio
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: '&copy;2016 Your name or company'
  description: Describe your website
  email: avi.v.parmar@gmail.com
  navlinks:
    - home: yes
      name: Home
      url: portfolio/
    - name: About
      url: about/
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - It's better to be a pirate than to join the NAVY
    - I am an aspiring 3D artist
    
  social:
    email: avi.v.parmar@gmail.com
    #facebook: full page or profile url in facebook
    #github: full profile url in github
    #gitlab: full profile url in gitlab
    #googleplus: full profile url in googleplus
    instagram: https://www.instagram.com/calicoanimations/
    #linkedin: full profile url in linkedin
    #stackoverflow: full profile url in stackoverflow
    #twitter: full profile url in twitter
    #whatsapp: wa.me service link
    youtube: https://www.youtube.com/channel/UCyQiFEKbdl9Ed9OwHt5rzzw
  style: default

markup:
  goldmark:
    renderer:
      unsafe: true
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
      
